services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
      - --certificatesResolvers.resolver.acme.email=${TRAEFIK_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - traefik-certs:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - moois
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - moois
  moois:
    build: .
    restart: unless-stopped
    environment:
      BETTER_AUTH_BASE_URL: ${BETTER_AUTH_BASE_URL}
      BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      GMAIL_USER: "${GMAIL_USER}"
      GMAIL_APP_PASSWORD: "${GMAIL_APP_PASSWORD}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moois.tls=true"
      - "traefik.http.routers.moois.rule=Host(`${MAIN_URL}`)"
      - "traefik.http.routers.moois.entrypoints=websecure"
      - "traefik.http.routers.moois.tls.certresolver=resolver"
      - "traefik.http.routers.moois.tls.domains[0].main=${MAIN_URL}"
      - "traefik.http.services.moois.loadbalancer.server.port=3000"
    depends_on:
      - db
    networks:
      - moois

networks:
  moois:
    external: false

volumes:
  db_data:
  traefik-certs:
